### ISSUE TITLE
Flutter version supported?

### ISSUE THREAD

**Issue by MichealReed** [asgardex/thorchain_explorer#32]
I attempted to run this today with flutter 2.1.0-13.0.pre.208 on the master channel, but even after resolving the pubspec dependency issues I could not get this to run. I am seeing this error throughout the codebase, but am not familiar enough with riverpods to know the recent changes that may be causing this.

```
The getter 'state' isn't defined for the type 'StateNotifierProvider<UserThemeNotifier, dynamic>'.

Try importing the library that defines 'state', correcting the name to the name of an existing getter, or defining a getter or field named 'state'.
```

**Comment by stuartkuentzel** [comment]
hey @MichealReed, did you try it on the "stable" flutter channel?

**Comment by stuartwk** [comment]
Closing this out, feel free to reopen if you are still having trouble running this
