### ISSUE TITLE
Pool APY should be * 100

### ISSUE THREAD

**Issue by rewtraw** [asgardex/thorchain_explorer#40]
Pool APY is displayed as raw value and not converted to a percent by multiplying by 100 

https://github.com/asgardex/thorchain_explorer/blob/ac7bcb7fb82f08dd3fb47c753fee6cb5ac6a2b62/lib/pool/pool_page.dart#L149

<img width="420" alt="Screen Shot 2021-04-22 at 9 47 35 AM" src="https://user-images.githubusercontent.com/1424776/115744430-cc48d080-a34f-11eb-8877-ce035c793845.png">
<img width="1091" alt="Screen Shot 2021-04-22 at 9 47 42 AM" src="https://user-images.githubusercontent.com/1424776/115744439-cd79fd80-a34f-11eb-8228-306bc87390cb.png">

**Comment by stuartwk** [comment]
Fix pushed for this 👍
